### ISSUE TITLE
File name like "file  name" read error

### ISSUE THREAD

**Issue by nanami-yu** [cmuench/inotify-proxy#22]
i have a shell like  /root/inotify-proxy  ./ | while read file
file name like "file  name"
but read "file name" 
multiple spaces merged into one
i can not get the real file name

**Comment by cmuench** [comment]
@nanami-yu thanks for reporting. I will have a look on it.

**Comment by cmuench** [comment]
@nanami-yu Can you try this?

```sh
/root/inotify-proxy ./ | while IFS= read -r file
do
  echo "$file"
done
````

**Comment by nanami-yu** [comment]
thank you I'll give it a try tomorrow
